# Install Config
api: 2
name: Focal
author: Prasad T
# Configuration
config:
  # Enabled Tasks
  tasks:
    update: true
    upgrade: true
    repo: true
    apt: true
    purge: true
  add_repo:
    bazel: true
    chrome: true
    docker: true
    github: true
    googlecloud: true
    gvisor: true
    podman: true
    signal: true
    spotify: true
    vscode: true
  flags:
    purge_enabled: true

  purge:
    - gnome-mines
    - gnome-sudoku
    - aisleriot
    - gnome-mahjongg
  install:
    apt:
      administration:
        - htop
        - apt-xapian-index
        - gparted
        - synaptic
        - bleachbit
      security:
        - gufw
      productivity:
        - pandoc-data
        - pandoc
        - texstudio
        - texlive-fonts-extra
        - texlive-formats-extra
        - texlive-fonts-recommended
        - texlive-science
        - texlive-xetex
        - texlive-luatex
        - texlive-pstricks
        - texlive-science
        - texlive-extra-utils
        - texlive-lang-english
        - texlive-lang-other
        - texlive-font-utils
        - texlive-publishers
        - gummi
      # Multimedia Tools. Photo Editors Converting tools, plex etc.
      multimedia:
        - audacity
        - vlc
        - gimp
        - handbrake
        - handbrake-cli
        - rawtherapee
        - darktable
        - mpv
        - pavucontrol
        - cheese
      # Tools related to development.
      development:
        - fish
        - curl
        - git
        - shellcheck
        - python3-pip
      # Everything Else
      other:
        - gnuradio
        - opensc
        - virt-manager
        - virt-viewer
        - libvirt-daemon-system
        - lm-sensors
        - chrome-gnome-shell
        - gnome-logs
        - gnome-system-monitor
        - gnome-calculator
        - gnome-usage
        - seahorse-nautilus
        - unrar
        - gnome-tweak-tool
      external:
        - google-chrome-stable
        - spotify-client
        - runsc
        - code
        - neofetch
        - google-cloud-sdk
        - yubioath-desktop
        - yubikey-manager-qt
        - yubikey-personalization-gui
        - yubikey-piv-manager
        - ubuntu-restricted-extras
        - ubuntu-restricted-addons
