# Version Config
api: 2
# Configuraion
version:
  number: 543
  name: 5.4.3
  changelog: fix classic snap install, fix ROS, spotify keys
# Stats reporting
stats:
  report: false
  node: https://stats.ae.prasadt.com/report
