# Version Config
api: 2
# Configuraion
version:
  number: 540
  name: 5.4.0
  changelog: Support installing snap Packages, Removed support for 14.04 Trusty
# Stats reporting
stats:
  report: false
  node: https://stats.ae.prasadt.com/report
