on:
  push:
    branches:
      - "**"
    paths-ignore:
      - ".gitignore"
      - ".envrc"
      - ".vscode/**"
      # Lets face it! Everyone needs more coffee to avoid typos!
      - "README.md"
      - "CONTRIBUTING.md"
      - ".github/workflows/labels.yml"
      - ".github/labels.toml"
      - ".github/**/*.md"
      # Lets ignore release workflow, because we do not really build any
      # binaries we are fine.
      - ".github/workflows/release.yml"
      # Also ignore docs workflow, script has nothing to do with it
      - ".github/workflows/docs.yml"
      - "docs/**"
      - "netlify.toml"
      - "mkdocs.yml"
      - "runtime.txt"
      - "docker-compose.yml"
    tags-ignore:
      - "**"
  pull_request:
    # Lets ignore docs in PR.
    # as we have docs workflow taking care of it.
    paths-ignore:
      - ".github/workflows/docs.yml"
      - "docs/**"
      - "netlify.toml"
      - "mkdocs.yml"
      - "runtime.txt"
      - "docker-compose.yml"
name: build
env:
  DEBUG: ci
jobs:
  shellcheck:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          chmod +x after-effects
          chmod +x tests/*.sh
      - name: Shellcheck
        run: ./tests/shellcheck.sh
  ubuntu:
    needs: [ "shellcheck"]
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        release: ["focal", "bionic", "groovy"]
    steps:
      - uses: actions/checkout@v2
      - name: Ubuntu ${{ matrix.release }}
        run: ./tests/local.sh --fix --distro ubuntu --release "${{ matrix.release }}"
  debian:
    needs: [ "shellcheck"]
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        release: [ "buster", "stretch"]
    steps:
      - uses: actions/checkout@v2
      - name: Debian ${{ matrix.release }}
        run: ./tests/local.sh --distro debian --release "${{ matrix.release }}"
  elementary:
    needs: [ "shellcheck"]
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        release: [ "juno-stable"]
    steps:
      - uses: actions/checkout@v2
      - name: Elementary ${{ matrix.release }}
        run:  ./tests/local.sh --distro elementary/docker --release "${{ matrix.release }}"
  arm:
    needs: [ "shellcheck"]
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        release: ["focal", "bionic", "groovy"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup binfmt and register arm binaries
        run: |
          sudo apt-get update || true
          sudo apt-get install -y qemu binfmt-support qemu-user-static
          sudo docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64

      - name: Test on ARM64 ${{ matrix.release }}
        run: ./tests/distro.sh "arm64v8/ubuntu" ${{ matrix.release }} "arm.yml"
