on:
  push:
    branches:
      - "**"
  pull_request:
name: build
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Prepare
        run: |
          chmod +x after-effects
          chmod +x tests/*.sh
      - name: Shellcheck
        run: ./tests/shellcheck.sh
  # Ubuntu
  ubuntu:
    needs: [ "shellcheck"]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: ["focal", "bionic", "hirsute"]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Ubuntu ${{ matrix.release }}
        run: ./tests/local.sh --build --debug-trace --fix --distro ubuntu --release "${{ matrix.release }}"
  # Debian
  debian:
    needs: [ "shellcheck"]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: [ "buster", "stretch"]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Debian ${{ matrix.release }}
        run: ./tests/local.sh --build --debug-trace --distro debian --release "${{ matrix.release }}"

  elementary:
    needs: [ "shellcheck"]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: [ "juno-stable"]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Elementary ${{ matrix.release }}
        run:  ./tests/local.sh --build --debug-trace --distro elementary/docker --release "${{ matrix.release }}"
  # Ubuntu ARM
  arm:
    needs: [ "shellcheck"]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: ["focal", "bionic", "groovy"]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Test on ARM64 ${{ matrix.release }}
        run: ./tests/local.sh --build --debug-trace --distro arm64v8/ubuntu --release "${{ matrix.release }}" --cfg config/arm.yml
  arm-debian:
    needs: [ "shellcheck"]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: ["stretch", "buster"]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Test on ARM64 ${{ matrix.release }}
        run: ./tests/local.sh --build --debug-trace --distro arm64v8/debian --release "${{ matrix.release }}" --cfg config/arm.yml
